spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_TABLE:openpulse}?cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true&serverTimezone=UTC
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true  # SQL 쿼리 출력
        format_sql: true  # SQL 포맷팅
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true
        generate_statistics: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    encoding: UTF-8

logging:
  level:
    org.hibernate.engine.jdbc.batch.internal: DEBUG
    org.hibernate.stat: DEBUG

github:
  token: ${GITHUB_TOKEN}