spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_TABLE:openpulse}?cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true&serverTimezone=UTC
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true
        generate_statistics: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.engine.jdbc.batch.internal: DEBUG
    org.hibernate.stat: DEBUG

github:
  token: ${GITHUB_TOKEN}